name: Docker Image CI

on:
  push:
    branches: [ v3.1 ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag testssl-web:3.1-latest --tag testssl-web:3.1-$(date +%s)


