name: Docker Image Publish

on: [push]

jobs:

  publish:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with: 
        submodules: 'true'
    - name: Build the Docker image
      env:
        GHCR_PAT: ${{ secrets.GHCR_PAT }}
      run: |
        echo $GHCR_PAT | docker login ghcr.io -u shartge --password-stdin
        docker build . --file Dockerfile --tag ghcr.io/shartge/testssl-web:3.1-latest
        docker push ghcr.io/shartge/testssl-web:3.1-latest


